Algoritmo "ExemploSE"
Var
   nome: caractere;
   salario: real;

Inicio
   escreva("Digite o seu nome: ")
   leia(nome)
   escreva("Digite o seu salario: ")
   leia(salario)
   se (salario>1220) entao
      escreval("Seu salario é maior que o salário mínimo")
   senao
      se(salario=1200)entao
         escreval("Você ganha um salario mínimo")
      senao
         escreval("Seu salario é menor que o salário mínimo")
      fimse
      fimse fimse

Fimalgoritmo