Algoritmo "ImprimeENQUANTO1a10"
// Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Imprime com ENQUANTO de 1 a 10! (função)
// Autor(a)    : Eduardo Rodrigues de Souza
// Data atual  : 16/11/2022
Var
// Seção de Declarações das variáveis 
   j:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Imprimindo de 1 a 10 enquanto!")
   j<-1
   enquanto j < 11 faca
   escreval(j)
   j<-j+1
   fimenquanto
   
   


Fimalgoritmo