Algoritmo "ImprimeFor100a1"
// Lógica de Programação
// Professor   : Marcos Monteiro
// Descrição   : Imprime de 100 a 1 usando FOR! (função)
// Autor(a)    : Eduardo Rodrigues de Souza
// Data atual  : 16/11/2022
Var
// Seção de Declarações das variáveis
   j:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Imprimindo de 100 a 1: ")
   para j de 100 ate 1 passo j-13 faca
        escreval(j)
   fimpara
   escreval("Fogo!!!")


Fimalgoritmo