Algoritmo "Imprimerepita1ate10"
// Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/11/2022
Var
// Seção de Declarações das variáveis
j:inteiro


Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Imprimindo de 1 a 10 Repita ate:")
   j<-1
   repita
         escreva(j)
         j<-j+1
         ate j > 50

Fimalgoritmo