Algoritmo "Multiplode2"
// Lógica de Programação
// Professor   : Marcos Monteiro
// Descrição   : Mostra os multiplos de 2 entre 0 a 100! (função)
// Autor(a)    : Eduardo Rodrigues de Souza
// Data atual  : 16/11/2022
Var
// Seção de Declarações das variáveis
   numero, k: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Multiplos de 2: ")
   numero<-2
   para k de 0 ate 100 passo numero faca
        escreval(k)
   fimpara


Fimalgoritmo